Resolved merge conflicts

diff --git a/.github/workflows/eks-setup-manual-trigger.yaml b/.github/workflows/eks-setup-manual-trigger.yaml
--- a/.github/workflows/eks-setup-manual-trigger.yaml
+++ b/.github/workflows/eks-setup-manual-trigger.yaml
@@ -45,15 +45,15 @@ jobs:
 
       # Create EKS cluster with CloudFormation
       # both AWSReservedSSO_Administrator-* role and an IAM role running this job should get full access to this EKS cluster
-    - name: Create EKS Cluster with CloudFormation
-      run: |
-        ADMIN_ROLE=$(aws iam list-roles --query "Roles[?contains(RoleName, 'aizhanyl')].RoleName | [0]" --output text)
-        if [ -z "$ADMIN_ROLE" ]; then
-          echo "Error: No matching IAM role found."
-          exit 1
-        fi
-        make cluster name=temporary-eks-cluster-${{ github.event.inputs.environment_stage }} version=1.27 role=$ADMIN_ROLE
-      working-directory: ./eks-cloudformation
+      - name: Create EKS Cluster with CloudFormation
+        run: |
+          ADMIN_ROLE=$(aws iam list-roles --query "Roles[?contains(RoleName, 'aizhanyl')].RoleName | [0]" --output text)
+          if [ -z "$ADMIN_ROLE" ]; then
+            echo "Error: No matching IAM role found."
+            exit 1
+          fi
+          make cluster name=temporary-eks-cluster-${{ github.event.inputs.environment_stage }} version=1.27 role=$ADMIN_ROLE
+        working-directory: ./eks-cloudformation
 
 
       # Login to EKS
